### ISSUE TITLE
Handle twitter contact updates better

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#244]
Since twitter's json per contact includes the last tweet, it constantly things they're being "updated", this could be handled better somehow.

**Comment by smurthas** [comment]
causing pretty huge file sizes in the Twitter Me data, making a priority.

**Comment by smurthas** [comment]
k, some more info here -- there are actually lots of fields that change all of the time, statuses_count, status, friends_count, followers_count, etc. It actually does feel like most of these represent a true "update" to the person's contact info, so what it really feels like we should do is just strip out the status field since that is already captured in the timeline feed. There is already working code to do this. It will only require manifest updates and a (somewhat optional) migration to clear out the status fields on old data.

**Comment by smurthas** [comment]
This is fixed as of the merge of pull #475
