### ISSUE TITLE
apikeys.json is poorly documented

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#296]
If I want a locker, but I only want to fill it with one or two data such as twitter and foursquare, it is unclear what to do with the other enteris in apikeys.json - should the user just leave them as 'copy&pastehere', should the user delete them? This requires the user to know JSON and to edit it by hand, as he or she might not remove the correct text, and end up with a unparsable file, and an unusable locker. 

I guess the correct answer is delete them, as it tries to parse the text as oauth params and breaks..

**Comment by othiym23** [comment]
Missing OAuth entries should (?) prevent the relevant services from even showing up in the services pane, so if you're uninterested in connecting to one or more services, removing the relevant key is what you want to do. We don't really have any documentation around how that file works right now, which is definitely something missing.

To your other point, the current release of the code is squarely targeted at developers who are familiar with Javascript and Node.js, and I hope it's safe to assume that all of them will be comfortable reading and writing JSON. It's a fair point that the current design is end-user unfriendly, but that's because we're driving the build out of the platform by concentrating on the hosted platform, and that's the level of engagement we're concentrating on right now. There's a lot of other stuff that needs to happen to make standalone locker setup & installation friendly to end users.

**Comment by elsmorian** [comment]
I can appreciate the dev-freindly end-user unfriendliness :)

I was mainly focusing on the lack of documentation for this file. You are correct that services without OAuth enteries do not show up, however if you just leave the default CODE HERE text from the .example file the services do show up, and then cause lots of OAuth errors in the logs. I can do a first pass of a wiki page for the apikeys file.

**Comment by othiym23** [comment]
Go for it! We're going to be doing a ton of documentation tasks over the next week in the run up to our public debut, but that's going to be oriented towards front-end developers / documenting the client-side locker API, so some of this more back-end stuff is going to be a little bit back-burnered for a month or so.

**Comment by elsmorian** [comment]
https://github.com/LockerProject/Locker/wiki/Apikeys.json
