### ISSUE TITLE
Error when running lockerbox.sh command

### ISSUE THREAD

**Issue by natea** [LockerProject/Locker#362]
When I run the lockerbox.sh command, I get the following error:

```
$ ./lockerbox.sh 
Git version 1.7.0.4 found.
Python version 2.6.1 found.
Node.js version 0.4.8 found.
npm version 1.0.101 found.
Activated virtual Python environment.
mongoDB version 1.6.5 found.
npm WARN async@0.1.9 package.json: bugs['web'] should probably be bugs['url']
npm WARN htmlparser2@1.0.0 package.json: bugs['web'] should probably be bugs['url']
npm WARN mongodb@0.9.6-15 package.json: bugs['web'] should probably be bugs['url']
npm WARN request@2.1.1 package.json: bugs['web'] should probably be bugs['url']
npm WARN wrench@1.1.0 package.json: bugs['web'] should probably be bugs['url']
npm WARN xmlbuilder@0.1.2 package.json: bugs['web'] should probably be bugs['url']
npm WARN npm@1.0.27 package.json: bugs['web'] should probably be bugs['url']
npm WARN clucene@0.2.2 package.json: bugs['web'] should probably be bugs['url']
npm ERR! Unsupported
npm ERR! Not compatible with your version of node/npm: clucene@0.2.2
npm ERR! Required: {"node":">= 0.4.9"}
npm ERR! Actual:   {"npm":"1.0.101","node":"0.4.8"}
npm ERR! 
npm ERR! System Darwin 10.8.0
npm ERR! command "node" "/Users/nateaune/code/lockerbox/local/bin/npm" "install"
npm ERR! cwd /Users/nateaune/code/lockerbox/Locker
npm ERR! node -v v0.4.8
npm ERR! npm -v 1.0.101
npm ERR! code ENOTSUP
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/nateaune/code/lockerbox/Locker/npm-debug.log
npm not ok
```

**Comment by ctide** [comment]
Updated lockerbox script to require correct node versions, and opened a pull request to loosen clucene's node version requirements.

**Comment by ctide** [comment]
Grab: https://github.com/LockerProject/lockerbox version of lockerbox, and upgrade your node to at least 0.4.9.

Thanks for pointing this out, btw!

**Comment by natea** [comment]
Ok, I grabbed the latest lockerbox.sh and re-ran it and now I'm getting this:

```
$ ./lockerbox.sh 
Git version 1.7.0.4 found.
Python version 2.6.1 found.
cmake not found!
```

**Comment by ctide** [comment]
What OS are you using?  Have you installed xcode/developer tools for OSX?  You'll need those to build node.  If I downgrade to node v0.4.8, I get the following output:

[ctide@Chris-Burkharts-MacBook-Pro-2 ~/dev/lockerbox] [master]:~$ ./lockerbox.sh
Git version 1.7.7 found.
Python version 2.7.1 found.
cmake version 2.8.5 found.
Node.js version 0.4.8 found.
Node.js version 0.4.9 or greater required!

Which is what you should get with cmake installed and node v0.4.8.

**Comment by natea** [comment]
yes, i have the XCode developer tools installed on my Snow Leopard machine.

Here's what is happening now when I upgrade my Node install and try to
run lockerbox.sh:

$ brew install node
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.
==> Downloading http://nodejs.org/dist/node-v0.4.12.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/homebrew/Cellar/node/0.4.12
==> make install
==> Caveats
Please add /usr/local/homebrew/lib/node_modules to your NODE_PATH
environment variable to have node libraries picked up.
==> Summary
/usr/local/homebrew/Cellar/node/0.4.12: 72 files, 7.6M, built in 8.8 minutes
(lockerbox)jazbook:lockerbox nateaune$ ./lockerbox.sh
Git version 1.7.0.4 found.
Python version 2.6.1 found.
cmake version 2.8.5 found.
Node.js version 0.4.8 found.
Node.js version 0.4.9 or greater required!

On Mon, Oct 24, 2011 at 10:54 PM, Chris Burkhart
reply@reply.github.com
wrote:

> What OS are you using?  Have you installed xcode/developer tools for OSX?  You'll need those to build node.  If I downgrade to node v0.4.8, I get the following output:
> 
> [ctide@Chris-Burkharts-MacBook-Pro-2 ~/dev/lockerbox] [master]:~$ ./lockerbox.sh
> Git version 1.7.7 found.
> Python version 2.7.1 found.
> cmake version 2.8.5 found.
> Node.js version 0.4.8 found.
> Node.js version 0.4.9 or greater required!
> 
> Which is what you should get with cmake installed and node v0.4.8.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/362#issuecomment-2512374

## 

Nate Aune - natea@jazkarta.com
http://www.jazkarta.com
http://card.ly/natea
http://tungle.me/natea
+1 (617) 517-4953

**Comment by ctide** [comment]
I think you have node installed in some other fashion than from brew.  What happens when you type `which node`?  Brew should have installed it to /usr/local/bin/node, which should be a symlink into /usr/local/Cellar/node/0.4.x/.  If it's not, you have node installed in some other fashion, and that version is older than what lockerbox wants right now.

Since we fixed the requirements in clucene, I'll lower the requirements in lockerbox as well.  If you repull lockerbox.sh now, it'll be happy with node 0.4.8, so you should be good to go either way.

**Comment by natea** [comment]
(lockerbox)jazbook:lockerbox nateaune$ which
node/usr/local/homebrew/bin/node(lockerbox)jazbook:lockerbox nateaune$
ls -l /usr/local/homebrew/bin/nodelrwxr-xr-x  1 nateaune  staff  30
Oct 25 16:41 /usr/local/homebrew/bin/node ->
../Cellar/node/0.4.12/bin/node

On Wed, Oct 26, 2011 at 12:59 PM, Chris Burkhart
reply@reply.github.com
wrote:

> I think you have node installed in some other fashion than from brew.  What happens when you type `which node`?  Brew should have installed it to /usr/local/bin/node, which should be a symlink into /usr/local/Cellar/node/0.4.x/.  If it's not, you have node installed in some other fashion, and that version is older than what lockerbox wants right now.
> 
> Since we fixed the requirements in clucene, I'll lower the requirements in lockerbox as well.  If you repull lockerbox.sh now, it'll be happy with node 0.4.8, so you should be good to go either way.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/LockerProject/Locker/issues/362#issuecomment-2533017

## 

Nate Aune - natea@jazkarta.com
http://www.jazkarta.com
http://card.ly/natea
http://tungle.me/natea
+1 (617) 517-4953

**Comment by zencuke** [comment]
It was a bit of a battle getting brew to install node-0.4.9. The brew formula for 4.9 requires gcc4.2 even though the default llvm compiler works fine for 4.9 and gcc4.2 is no longer installed by xCode. (I reported this problem to brew git issue list so hopefully it will be fixed soon.) I needed to uninstall node-0.6.2 because the npm clucene build kept finding it even though I had tarball install of node-0.4.9. Probably my fault but I couldn't figure out why. I finally deleted both versions of node; backed up the brew git repository to 0.4.9; edited the formula to take out fails_with_llvm which finally got me a brew installed version of 4.9. I took its advice and added NODE_PATH to my .bashrc  and lo and behold lockerbox.sh finally installed and started. It gave a few errors along the way but I have no idea whether they are significant (clucene library not loaded. so sad, couldn't find contactsviewer) so I'll wait on those until/unless they cause me trouble. Currently I have no idea what Locker actually does so that will be a while. ;-) My  usual process is 1) install 2) experiment 3) If all else fails read documentation. It looks like I need to do 3)

Thanks for the advice and assistance.
