### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by akshayakrsh** [LockerProject/Locker#450]
Hi

I am getting the Socket Hangup error in my code for very long and after contacting the NodeJS team, I discovered the problem has been solved in the new version i.e. 0.6.1. I wanted to know that if I use this version, will Locker work properly?

Thanks
Akshaya

**Comment by ctide** [comment]
Not for a while, we require a bunch of libraries that aren't upgraded yet.  We do have a branch in progress, but we're blocked on those libraries for now.

**Comment by akshayakrsh** [comment]
Oh...Can you please suggest me how can I get around this error with the version 0.4.9 of node js? sadly there's no documentation available for that.

**Comment by ctide** [comment]
Where are you seeing a socket hangup?  Can you paste the log of what's happening in your locker leading up to the crash?

**Comment by akshayakrsh** [comment]
Its in my custom code...the log is:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: socket hang up
    at Socket.<anonymous> (http.js:1286:45)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)
warn: Forever detected script exited with code: 1
warn: Forever restarting script for 1 time

**Comment by akshayakrsh** [comment]
Hello Chris,

Any idea about how I can do this? Its really a pain now. And what is the ETA for supporting higher versions of nodejs?

**Comment by ctide** [comment]
https://github.com/nodejitsu/node-http-proxy/pull/152 is the most pressing issue that I'm aware of blocking us from using node v0.6.  Once that's resolved, we'll figure out what the next blocker is, but who knows how many things still need to be updated before we can support 0.6.

Unfortunately, that error just means that the process died because whatever it had a connection to died, so it's not really possible to debug.  Sorry! :(
