### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#453]
I connected all my services and eventually got this:

https://gist.github.com/1374669

**Comment by quartzjer** [comment]
It was the links process that out of mem'd, then due to the broken http socket core crashed, two issues!

On the socket I've looked at that before and think it might be a node 0.4 issue, and couldn't reliably reproduce.

On the links it was probably downloading a large or streaming link, it sends the http headers to limit but not all servers obey, might have to not use request and use http directly there.

**Comment by othiym23** [comment]
Jer, could you dig into this a little and investigate?

**Comment by quartzjer** [comment]
I've not seen this at all again, and have gone through these steps a few times.  I suspect it was the event system slamming a connector simultaneously, which are now serialized much more safely. We can re-open this if it happens again...
