### ISSUE TITLE
Per-synclet config isn't.

### ISSUE THREAD

**Issue by othiym23** [LockerProject/Locker#537]
When paginating, much use is made of the config object, which allows the setting of a next runtime as well as tracking the current state of pagination. Right now, there is one of these config objects per me.json wad, which means that it's, to quote @smurthas, bad news bears if there's more than one paginating synclet running at the same time.

**Comment by quartzjer** [comment]
There's a bit of undocumented magic being unearthed here, which is good to uncover :)

As long as each synclet uses their own namespace within config (config.mysynclet.page), they are all good, and they can't overrun each other because they're changes are merged:
         info.config = lutil.extend(true, info.config, response.config);

Also, some synclets use config to talk to each other, like the bodymedia ones put discovered tasks in an array queue that another synclet processes from when it runs.

**Comment by quartzjer** [comment]
Stale config data from another synclet can get re-extened back in, doh!

Possible option, run one synclet at a time per connector, serialize them, possibly safer overall.
