### ISSUE TITLE
Service overload

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#587]
When an app uses a bunch of services, they don't all fit on the app card: http://bit.ly/wc4H0K

@merc3po, assigning you as we will need a mockup. Once that's don't someone can implement.

**Comment by merc3po** [comment]
Let's use small icons here, since we're teaching people to click them to connect services anyway. These icons are 16x16. 

https://skitch.com/e-merc3po/g36ih/16x16-icons-appreg

**Comment by smurthas** [comment]
That looks awesome! That should get us father along.

**Comment by temas** [comment]
Should we maybe change the wording of "Connect" to "Services" or similar and show them in the same full/partial opacity style as the bottom left of the You screen?  This way it's consistent and you can always see all the services used by an app.

**Comment by merc3po** [comment]
So the ones that we display here are ONLY the ones that are not already connected by the user. Hence "Connect" as a verb directing them to connect those services rather than a listing of the "Services" - though I 100% agree that that would make the most sense if it was a listing of the services used by the app.
