### ISSUE TITLE
"repository" field of package.json objects causes confusion

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#617]
We are very inconsistent as to what fields are in the repository section of package.json and what fields are at the top level. This is hard to work with both when building an app and when working with the Locker code.

**Comment by quartzjer** [comment]
NPM uses http://wiki.commonjs.org/wiki/Packages which allows the
invention of new top-level fields (that aren't reserved), but the
publish hooks npm has in couch will sanitize since it merges the
fields as new versions are published.  "repository" was the only field
available in order to use everything as-is, but I agree we should
document _clearly_ which fields are used in the package top level
versus in the repository :)

On Tue, Jan 24, 2012 at 2:38 PM, Simon Murtha-Smith
reply@reply.github.com
wrote:

**Comment by temas** [comment]
I feel we've largely resolved this through OOB discussions.  Perhaps some fields need to go into config, but we've already started down this path.  Motion to close.

**Comment by smurthas** [comment]
agreed.
