### ISSUE TITLE
"upserting" a connector puts in the service map

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#624]
Even if a connector hasn't been authed, it ends up in the map. Really, connectors should only show up in map if they are authed.

**Comment by quartzjer** [comment]
This semantic changed, so that connectors can exist and be preserved even in an un-authed state (either by choice or by error) at any point in their lifecycle (without loosing data).  To know if it's auth'd or not, there's a .auth object and .authed timestamp, the rough consensus (between temas/eric) so far is to use the .auth object as the flag to know it's current state or not.
