### ISSUE TITLE
Lockerproject.org doesn't mention other deps

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#626]
Lockerproject.org download section mentions Git and Python are needed, but not the curl, build-essential and libssl-dev packages (Which by default are not installed in Debian Squeeze and probably a few other distros.)

**Comment by mdz** [comment]
curl is only used to download lockerbox.sh, which could be done by saving it from the browser or with wget or various other ways as well. I guess I considered the curl command line to be an example, rather than an API. :-)

The website is in the "lockerproject.org" repo adjacent to this one, btw, so we should probably move this over there

**Comment by merc3po** [comment]
Done: https://github.com/LockerProject/lockerproject.org/issues/1
