### ISSUE TITLE
lockerbox fails with current Locker

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#881]
It doesn't run make. Once it does, the Makefile will need logic to update PATH the same way ./locker does, to find the dependencies installed by lockerbox

**Comment by amcjen** [comment]
Not clear on what this bug is.  In locker, the only path handling is: NODE_PATH=Common/node.  There is also a NODE_PATH setting in the lockerbox Makefile, but to the same directory, and it's for an oldtest target.

Additionally, I was able to successfully build the lockerbox locker on my machine, following the documentation.  If you're getting failures when building, would you post what commands you're running, on what platform, and I'll use that to try to reproduce?

**Comment by mdz** [comment]
I'm talking about PATH itself, not the node PATH.  Without the right PATH, it won't even be able to launch node!

**Comment by mdz** [comment]
It would have worked on your machine because you already have the dependencies installed, but lockerbox is supposed to work even if you don't have them yet

**Comment by amcjen** [comment]
Well, for OS X, we're assuming you have the XCode toolbase installed already, which will def. have those tools installed.  If you are on another Ubuntu, this isn't the case.

I will spin up a fresh Ubuntu VM and add path stuff.

**Comment by mdz** [comment]
XCode comes with node.js and mongodb?
